accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', IndexPageView.as_view(), name='index'),
    path('', include('main.urls')),

    path('i18n/', include('django.conf.urls.i18n')),
    # path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <!-- <title>Simple Django Login and Registration</title> -->

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome-free-5.15.4-web/css/all.css' %}" rel="stylesheet">
    <script src="{% static 'vue.js' %}"></script>
    <script src="{% static 'axios.js' %}"></script>
</head>

<body>
<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>


<!-- <img src="{% static 'cube.jpg' %}"> -->
<style type="text/css">
    .active-item {
        /*background-color: white;*/
        color: black;
        border-top: 2px solid #9a9da0;
        border-left: 2px solid #9a9da0;
        border-right: 2px solid #9a9da0;
        /*border-bottom: 5px solid #9a9da0;*/
        border-radius: 0 10px 0 0;
        /*box-shadow: 0 0 10px rgba(0,0,0,0.5); padding: 3px;*/

    }
    .inactive-item {
        border-bottom: 2px solid #9a9da0;
    }
</style>


<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <!-- <a class="navbar-brand" href="/">{% trans 'Home' %}</a> -->

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                    {% if request.resolver_match.url_name == "storages" %}
                    <div class="active-item">
                    {% else %}
                    <div class="inactive-item">
                    {% endif %}
                        <a class="nav-link" href="{% url 'storages' %}">Хранилища</a>
                    </div>
                </li>
                {% endif %}
                <li class="nav-item">
                    {% if request.resolver_match.url_name == "docs" %}
                    <div class="active-item">
                    {% else %}
                    <div class="inactive-item">
                    {% endif %}
                        <a class="nav-link" href="{% url 'docs' %}">Документы</a>
                    </div>
                </li>
                <li class="nav-item">
                    {% if request.resolver_match.url_name == "history" %}
                    <div class="active-item">
                    {% else %}
                    <div class="inactive-item">
                    {% endif %}
                        <a class="nav-link" href="{% url 'history' %}">История</a>
                    </div>
                </li>
                <li class="nav-item">
                    {% if request.resolver_match.url_name == "about" %}
                    <div class="active-item">
                    {% else %}
                    <div class="inactive-item">
                    {% endif %}
                        <a class="nav-link" href="{% url 'about' %}">Справка</a>
                    </div>
                </li>
<!--                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>
                </li> -->


            {% endif %}
        </ul>

        <ul class="navbar-nav">
<!--             <li class="nav-item">

                {% get_current_language as language_code %}
                {% get_available_languages as languages %}
                <form action="{% url 'set_language' %}" method="post" class="form-inline">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}"/>
                    <div class="form-group">
                        <select name="language" class="form-control" id="language-field" onchange="this.form.submit()">
                            {% for code, name in languages %}
                                <option value="{{ code }}" {% if code == language_code %} selected="selected"{% endif %}>
                                    <div class="">{{ code }}</div>
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </form>
                </li> -->

                {% if request.user.is_authenticated %}
                    <div class="btn-group" role="group" aria-label="Basic example">
                      <button type="button" class="btn btn-info"><i class="fa fa-user" style="margin-right: 10px;"></i>{{ request.user.username }}</button>
                      {% if user.is_superuser %}
                      <a href="{% url 'accounts:change_password' %}" class="btn btn-warning">
                        <i class="fa fa-key" style="margin-right: 10px;"></i>Сменить пароль
                      </a>
                      {% endif %}
                      <button class="btn btn-light"><a href="{% url 'accounts:log_out' %}" ><i class="fa fa-sign-out-alt" style="margin-right: 10px;"></i>Выйти</a></button> 
                    </div>
                {% endif %}


            
        </ul>
    </div>

</nav>

<div class="container-fluid mt-3">

    {% bootstrap_messages %}

    {% block content %}
        No content.
    {% endblock %}

</div>

</body>
</html>